<a href="https://colab.research.google.com/github/kwanda2426/projects/blob/main/Mlondie_ask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Create a dataframe with 15 participant IDs and their fitness levels (0, 1, or 2) for 14 days.

## Create the initial dataframe

### Subtask:
Create a DataFrame with 15 participant IDs and their initial randomly assigned fitness levels (0, 1, or 2).


In [1]:
import pandas as pd
import numpy as np

participant_ids = [f'Participant_{i+1}' for i in range(15)]
initial_fitness_levels = np.random.randint(0, 3, 15)

df = pd.DataFrame({
    'Participant_ID': participant_ids,
    'Initial_Fitness_Level': initial_fitness_levels
})

df_1 = df.copy()

In [2]:
import numpy as np
df_2 = df.copy()

# Define parameters for each fitness level
fitness_params = {
    0: {'mean': 6000, 'std_dev': 600},
    1: {'mean': 7500, 'std_dev': 500},
    2: {'mean': 9000, 'std_dev': 700}
}

# Generate daily step counts for 14 days
for day in range(1, 15):
    column_name = f'Steps Day {day}'

    # Create an empty list to store steps for each person
    steps = []

    # Loop through each row in df
    for level in df['Initial_Fitness_Level']:
        mean = fitness_params[level]['mean']
        std_dev = fitness_params[level]['std_dev']
        value = np.random.normal(mean, std_dev)
        value = round(value)
        value = min(max(value, 3000), 15000)  # clip between 3000 and 15000
        steps.append(int(value))

    # Add column to DataFrame
    df_2[column_name] = steps

# Display the updated DataFrame with step counts
steps_cols = [col for col in df_2.columns if 'Part' in col]+[col for col in df_2.columns if 'Steps' in col]


In [4]:
# Select the columns containing step counts
step_columns = [f'Steps Day {day}' for day in range(1, 15)]
steps_array = df_2[step_columns].values

# Display the shape of the resulting NumPy array to confirm
print("Shape of the steps array:", steps_array.shape)

# Display the first few rows of the NumPy array
print("First 5 rows of the steps array:")
print(steps_array[:5])

Shape of the steps array: (15, 14)
First 5 rows of the steps array:
[[7779 7220 7010 6983 7412 7104 8497 7298 8040 7305 8326 7037 7805 7775]
 [7109 7634 7035 8022 6980 7373 7563 7617 7245 7469 7719 7858 7555 7658]
 [7568 7661 7677 7059 7361 7171 7403 7867 6524 7094 7670 7185 6834 7505]
 [6711 7773 8109 7302 8201 8235 7591 7706 7231 7475 6880 8534 8029 8105]
 [6992 6371 5863 5997 5380 6629 7115 5246 4974 6816 5706 6667 6638 6502]]


In [ ]:
display(df_2[steps_cols])